### ISSUE TITLE
jAgar

### ISSUE THREAD

**Issue by Faris90** [xa/facebook-group-dump#2]
When I compiled I try to run the jar but it doesn't compile...

**Comment by xa** [comment]
Unrelated question to this project as jAgar is completly different project.
But you should try compiling jAgar with specifically Java 8 JDK. It's a very old code which relied on really obscure Java AWT calls which may be deprecated in later java versions.
You should probably rewrite the whole renderer to use something that utilizes gpu for rendering, like libGDX.
